[package]
name = "get_cover_path"
version = "0.1.0"
authors = ["Po-Yeh Chen <supermariobros374@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcre2 = "*"
mpd = "*"
